lesson_2
89081314528/univercity pull request #1
Opened 2022-01-27 08:17 UTC by 89081314528

2022-01-28 23:30 UTC, DisterRU requested changes

2022-01-28 23:30 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/controller/FacultyController.java
> +    }
Понятное дело, что в уроке был показан способ работы через ResponseEntity, однако использовать их в тех случаях, когда не надо отдельно спекать (с помощью хидеров, например) ответ. не требуется.
Здесь бы гораздо лучше зашел способ с исключениями и @ResponseStatus из 2го курса.

2022-01-28 23:30 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/controller/FacultyController.java
> +    @GetMapping("/get/{id}")
Следует убрать /get.
Чтобы все CRUD методы висели на одном эндпоинте (адресе) и отличались только наличием/отсутствием параметра id.

2022-01-28 23:30 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/controller/FacultyController.java
> +    @DeleteMapping("/delete/{id}")
/delete нужно стереть из адреса по аналогии с get.

2022-01-28 23:30 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/service/FacultyService.java
> +        return facultiesByColour;
На уроке 2.8 был пройден Stream API, который был бы здесь очень уместен.

2022-01-28 23:30 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/service/FacultyService.java
> +        return facultyMap.values();
Лучше оборачивать в копию или unmodifiable коллекцию.
Это в общем случае позволит защитить нашу коллекцию от изменений в тех местах, где ее запросят другие классы.

2022-02-04 12:31 UTC, 89081314528 commented on src/main/java/ru/hogwarts/university/service/FacultyService.java
> +        return facultiesByColour;
Я пока не успела пройти урок со Stream API, не могу применить

2022-02-10 22:51 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/service/FacultyService.java
> +    public void deleteFaculty (Long facultyId) { // может возвращать Faculty?
На текущем этапе вернуть faculty возможно, но в случае с базой данных метод удаления репозитория не будет возвращать ничего.
Потому тут лучше сразу сделать этот метод войдовым.
Однако если факультет не найден, стоит кидать из него исключение.
Потому все в общем-то корректно.

2022-02-10 22:51 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/exception/StudentNotFound.java
> +public class StudentNotFound extends RuntimeException {
Имена классов-исключений должны заканчиваться на слово Exception

2022-02-13 16:30 UTC, 89081314528 commented on src/main/java/ru/hogwarts/university/controller/FacultyController.java
> +        facultyService.deleteFaculty(facultyId);
в случае успеха здесь вернется ок, а в случае неуспеха в сервисе кидается исключение

2022-02-16 17:59 UTC, merged