add database
89081314528/univercity pull request #2
Opened 2022-01-27 15:32 UTC by 89081314528

2022-01-28 23:44 UTC, DisterRU requested changes

2022-01-28 23:44 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/service/FacultyService.java
> +        Collection<Faculty> allFaculties = facultyRepository.findAll();
Вместо получения всех сущностей и фильтрации в цикле имеет смысл объявить метод findByColor(String color) в репозитории, а спринг реализует его в виде запроса к бд.
Тогда в данном методе не придется писать цикл.

2022-01-28 23:44 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/service/FacultyService.java
> +    FacultyRepository facultyRepository;
private final

2022-02-10 22:55 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/controller/FacultyController.java
>      }
В ситуации, когда вернуть нечего, лучше возвращать response entity, как и было сделано.
void методы в контроллерах не очень хорошая идея.

2022-02-10 22:55 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/exception/FacultyNotFound.java
> +public class FacultyNotFound extends RuntimeException {
Имена классов-исключений должны заканчиваться на слово Exception

2022-02-10 22:56 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/exception/StudentNotFound.java
> +public class StudentNotFound extends RuntimeException{
Имена классов-исключений должны заканчиваться на слово Exception

2022-02-10 22:56 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/model/Faculty.java
> +    private String colour;
Смысла переименования не вижу, но раз так больше нравится, то ок. :)

2022-02-10 22:58 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/service/FacultyService.java
> +        }
Лучше заменить на 
```
Faculty faculty = facultyRepository.findById(facultyId)
    .orElseThrow(FacultyNotFoundException::new);
facultyRepository.delete(faculty);
```

2022-02-10 23:00 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/service/StudentService.java
>          studentRepository.deleteById(studentId);
Комментарий аналогичен предыдущему сервису.

2022-02-13 16:36 UTC, 89081314528 commented on src/main/java/ru/hogwarts/university/controller/FacultyController.java
>      }
В случае успеха вернется статус ок, а случай, если faculty равен null, обрабатывается в сервисе, там кидается исключение

2022-02-13 16:36 UTC, 89081314528 commented on src/main/java/ru/hogwarts/university/controller/StudentController.java
>      }
В случае успеха вернется статус ок, а случай, если faculty равен null, обрабатывается в сервисе, там кидается исключение

2022-02-13 16:36 UTC, 89081314528 commented on src/main/java/ru/hogwarts/university/exception/FacultyNotFound.java
> +public class FacultyNotFound extends RuntimeException {
исправила

2022-02-13 16:36 UTC, 89081314528 commented on src/main/java/ru/hogwarts/university/exception/StudentNotFound.java
> +public class StudentNotFound extends RuntimeException{
исправила

2022-02-13 16:37 UTC, 89081314528 commented on src/main/java/ru/hogwarts/university/model/Faculty.java
> +    private String colour;
хотела сделать, чтобы колонка и поле назывались одинаково) )

2022-02-13 16:42 UTC, 89081314528 commented on src/main/java/ru/hogwarts/university/service/StudentService.java
>          studentRepository.deleteById(studentId);
исправила

2022-02-13 22:01 UTC, DisterRU approved these changes

2022-02-13 22:01 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/service/FacultyService.java
> +        Faculty faculty = facultyRepository.findById(facultyId).orElseThrow(FacultyNotFoundException::new);
Чтобы проверить элемент на существование есть метод того же репозитория existsById.
Он вернет буль, который уже можно обработать в стандартном ифе.

2022-02-13 22:01 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/service/StudentService.java
>          return student;
Инлайн

2022-02-13 22:01 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/service/StudentService.java
> +        Student student = studentRepository.findById(studentId).orElseThrow(FacultyNotFoundException::new);
existsById

2022-02-16 19:13 UTC, closed without merging