lesson-4
89081314528/univercity pull request #3
Opened 2022-02-09 19:32 UTC by 89081314528

2022-02-12 22:57 UTC, DisterRU requested changes

2022-02-12 22:57 UTC, DisterRU commented on src/main/java/ru/hogwarts/university/repository/FacultyRepository.java
> +    List<Faculty> findByNameIgnoreCaseOrColourIgnoreCase(String name, String colour);
А если какое-то из значений будет равно нуллу?
Предлагаю не усложнять жизнь себе и бд проверками на нулл, если их можно легко произвести внутри кода.
Работа с нуллами в бд может привести к интересным результатам.

2022-02-13 16:49 UTC, 89081314528 commented on src/main/java/ru/hogwarts/university/repository/FacultyRepository.java
> +    List<Faculty> findByNameIgnoreCaseOrColourIgnoreCase(String name, String colour);
List<Faculty> findByNameIgnoreCaseOrColourIgnoreCase(@RequestParam (required = false) String name,
                                                         @RequestParam (required = false) String colour)
у меня есть параметр (required = false), и в случае, если какой-то из параметров равен null, то все нормально работает

2022-02-13 18:03 UTC, 89081314528 commented on src/main/java/ru/hogwarts/university/repository/FacultyRepository.java
> +    List<Faculty> findByNameIgnoreCaseOrColourIgnoreCase(String name, String colour);
исправила

2022-02-16 19:13 UTC, closed without merging